### ISSUE TITLE
API zwraca zajęte terminy pod kluczem AvailableVisitsTermPresentation

### ISSUE THREAD

**Issue by patrykpalej** [pawliczka/LuxmedSniper#10]
Wyniki, które są zwracane przez API pod kluczem `AvailableVisitsTermPresentation` mają pole `IsFree` oznaczone jako `False`. Nie udało mi się znaleźć takich wyników, które miały by tam `True`. Jest to dziwne ponieważ:
1. `AvailableVisitsTermPresentation` powinien zwracać terminy dostępne
2. Używając tych samych filtrów wyszukiwania (miasto, rodzaj lekarza, zakres dat) w przeglądarce dostaję wyniki, których API nie zwraca

**Comment by pawliczka** [comment]
Zobacz teraz z nowym api
