### ISSUE TITLE
No visits found by tool since a couple of days

### ISSUE THREAD

**Issue by radek-t** [pawliczka/LuxmedSniper#18]
Hi Paweł, 

First things first - many thanks for putting this together. I've been a heavy user for 
the past couple of months & found it really useful. Kudos!

There's one thing I've noticed recently. Not sure if the API has changed or if there's another reason, but the tool doesn't find any visits anymore, even in cases when there's an abundance of them to chose from. 

This is probably not related to captcha's introduced some time ago, as I recall the tool was working fine for several weeks despite them being in place both in the mobile app, as well as the web app (at least for my very active user).

I've ensured all the params I use are correct.
My last notifications about properly found visits are from March the 28th. 

Thanks in advance for looking into this!

**Comment by BeniaminK** [comment]
Same problem here: authentication works properly, however there are no visits returned from the API

**Comment by BeniaminK** [comment]
This PR updated the API:
https://github.com/pawliczka/LuxmedSniper/pull/20
