### ISSUE TITLE
Pobieranie access tokenu przestalo dziala

### ISSUE THREAD

**Issue by mateuszaaa** [pawliczka/LuxmedSniper#33]
Przy probie odpalenia aplikacjia w momencie requestowania access tokena zwracany jest json z informacja o niekomaptybilnosci

```
{'Errors': [{'ErrorCode': 301, 'Message': 'The currently installed version of the application is not supported by the new Patient Portal system. Please update the application to the latest version to use it.', 'AdditionalData': {'ShopUrl': 'market://details?id=pl.luxmed.pp', 'FallbackUrl': 'http://play.google.com/store/apps/details?id=pl.luxmed.pp', 'Title': 'Update the application'}}]}
```
Chetnie pomoge jednakze przydalyby sie jakies wskazkowki ;)

**Comment by aokomorowski** [comment]
@mateuszaaa błąd leci z powodu złego User-Agent headera, zwykły header skopiowany z Mozilli powinien dać radę. Do tego zmieniło się API, można teraz robić searcha po kilku practitionerach równocześnie. Jak podejrzysz requesty w przeglądarkowej wersji to ogarniesz różnice w parametrach.
