### ISSUE TITLE
Incorrect possible appointments returned

### ISSUE THREAD

**Issue by crit54** [pawliczka/LuxmedSniper#6]
When I try to find appointment using your script for `usg tarczycy` in Warsaw (passing 1 as cityId and 4360 as serviceVariantId) I receive a lot of possible results. But afterwards trying to find apppointments using Luxmed website or android app shows none possible appointments (or very few). 

I also tried to test some other service, for example `Optometrysta - dobór szkieł okularowych` (12754) and for that case the results seem to be OK.

Does luxmed hide possible visits for some groups of patients? But your script logs me there so it should be the same.

Or maybe it has something to do with user agent (which iPhone) in your script or some parameters which you pass to luxmed API? Maybe these are not passed when a human uses browses website or uses android app.

**Comment by pawliczka** [comment]
Maybe try to play with the payerId field

**Comment by tuszyn** [comment]
Hi, I encountered exaclty the same problem. I tried changing the payerID multiple times, but it didn't work. Unfortunately, I don't know how to fix it. Could you look into this?

**Comment by patrykpalej** [comment]
Same problem here
